<em><a name="PastaAtdPad" id="PastaAtdPad"></a>Pasta de atendimento padrão</em><br />
  Caminho da pasta e nome do arquivo:<em> &quot;\\nome_do_computador\atendimento\nome_da_UO\nome_produto\cliente\RACxxxxyyyyyy-nome_arquivo.ext&quot;<br />
  <br />
  </em>
<table width="100%" border="0">
  <tr>
    <td width="9%"><strong>Exemplos:</strong></td>
    <td width="91%">&quot;\\formosa\atendimento\tributario\sistema tributario\pmjp\RAC2007000345-ata de reuni&atilde;o.pdf&quot; </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&quot;\\formosa\atendimento\orcamentario\orca\pmni\RAC2007000346-conversa&ccedil;&atilde;o com fulano de tal.rtf&quot; </td>
  </tr>
  <tr>
  	<td>&nbsp;</td>
	<td>&quot;\\formosa\atendimento\bi\consultoria\caruaru\RAC2007000340-comparativo pessoal afastado por evento.rep&quot; </td>
  </tr>	
</table>
<br />

